# Generated by Django 5.1.4 on 2025-02-10 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
